# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_color_theme: ocean # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
url: # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: # does not include hostname
title: Farley-Fu's blog
description: > # this means to ignore newlines until "Language & timezone"
  生命不止，折腾不息。


## => Language and Timezone
##############################
lang: zh # the language of your site, "en" (default, English), "zh"(简体中文), "zh-Hans"(简体中文), "zh-Hant"(繁體中文)
timezone: # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  name: Farley-Fu
  email: fuyangily@126.com # your Email address e.g. someone@site.com
  facebook: # your Facebook username
  twitter: # your Twitter username
  github: # your GitHub username
  linkedin: # your Linkedin username
  googleplus: # your Google+ username
  weibo: # your Weibo username
  douban: # your Douban username


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: farley-fu/farley-fu.github.io
repository_tree: master


## => Paths
##############################
paths:
  base: /


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->
excerpt_type: html # text (default), html

## TOC
toc:
  selectors: # "h1,h2,h3" (default)

## Markdown Enhancements

# Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

# Mermaid
mermaid: # false (default), true

# Chart
chart: # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Comments
##############################
## Disqus
disqus:
  shortname: # the Disqus shortname for the site

## Gitalk
# please refer to https://github.com/gitalk/gitalk for more info.
gitalk:
  clientID: dab378fb38e20f420ee3 # GitHub Application Client ID
  clientSecret:  981bbf23a8ace1553b1217b1ed5367b35b76aade # GitHub Application Client Secret
  repository: farley-fu.github.io # GitHub repo
  owner: farley-fu # GitHub repo owner
  admin: farley-fu # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
    # - your GitHub Id


## => Pageview
##############################
## Leancloud
leancloud:
  app_id: PuqyinyakXYL5MQvMQiMje7q-gzGzoHsz # LeanCloud App id
  app_key: RvuqGlCMCxqJffpX3pgKPb39 # LeanCloud App key
  app_class: click_num # LeanCloud App class


## => Analytics
##############################
## Google Analytics
ga_tracking_id: # Google Analytics id for the site
ga_anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      license: true
      aside:
        toc: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji